name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: '0 0 * * *'  # runs every 24 hours
  workflow_dispatch:      # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
